Listing '.'...
Listing './bin'...
Listing './include'...
Listing './lib'...
Listing './lib/python3.5'...
Listing './lib/python3.5/site-packages'...
Listing './lib/python3.5/site-packages/_pytest'...
Listing './lib/python3.5/site-packages/_pytest/_code'...
Listing './lib/python3.5/site-packages/_pytest/assertion'...
Listing './lib/python3.5/site-packages/_pytest/vendored_packages'...
Listing './lib/python3.5/site-packages/argparse-1.4.0.dist-info'...
Listing './lib/python3.5/site-packages/astroid'...
Listing './lib/python3.5/site-packages/astroid/brain'...
Listing './lib/python3.5/site-packages/astroid/interpreter'...
Listing './lib/python3.5/site-packages/astroid/interpreter/_import'...
Listing './lib/python3.5/site-packages/astroid/tests'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/SSL1'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/absimp'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/absimp/sidepackage'...
Compiling './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/all.py'...
***   File "./lib/python3.5/site-packages/astroid/tests/testdata/python2/data/all.py", line 7
    def func(): print 'yo'
                         ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/appl'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/contribute_to_namespace'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/contribute_to_namespace/namespace_pep_420'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/find_test'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/foogle'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/foogle/fax'...
Compiling './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/invalid_encoding.py'...
***   File "./lib/python3.5/site-packages/astroid/tests/testdata/python2/data/invalid_encoding.py", line 0
SyntaxError: unknown encoding: lala

Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/lmfp'...
Compiling './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/module.py'...
***   File "./lib/python3.5/site-packages/astroid/tests/testdata/python2/data/module.py", line 32
    except ValueError, ex:
                     ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/module1abs'...
Compiling './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/module2.py'...
***   File "./lib/python3.5/site-packages/astroid/tests/testdata/python2/data/module2.py", line 78
    exec 'c = 3'
               ^
SyntaxError: Missing parentheses in call to 'exec'

Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/namespace_pep_420'...
Compiling './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/noendingnewline.py'...
***   File "./lib/python3.5/site-packages/astroid/tests/testdata/python2/data/noendingnewline.py", line 21
    print 'a'
            ^
SyntaxError: Missing parentheses in call to 'print'

Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/notamodule'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/package'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/package/subpackage'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/path_pkg_resources_1'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/path_pkg_resources_1/package'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/path_pkg_resources_2'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/path_pkg_resources_2/package'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/path_pkg_resources_3'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/path_pkg_resources_3/package'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/path_pkgutil_1'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/path_pkgutil_1/package'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/path_pkgutil_2'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/path_pkgutil_2/package'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/path_pkgutil_3'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/path_pkgutil_3/package'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/unicode_package'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python2/data/unicode_package/core'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/SSL1'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/absimp'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/absimp/sidepackage'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/appl'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/contribute_to_namespace'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/contribute_to_namespace/namespace_pep_420'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/find_test'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/foogle'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/foogle/fax'...
Compiling './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/invalid_encoding.py'...
***   File "./lib/python3.5/site-packages/astroid/tests/testdata/python3/data/invalid_encoding.py", line 0
SyntaxError: unknown encoding: lala

Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/lmfp'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/module1abs'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/namespace_pep_420'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/notamodule'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/package'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/package/subpackage'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/path_pkg_resources_1'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/path_pkg_resources_1/package'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/path_pkg_resources_2'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/path_pkg_resources_2/package'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/path_pkg_resources_3'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/path_pkg_resources_3/package'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/path_pkgutil_1'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/path_pkgutil_1/package'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/path_pkgutil_2'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/path_pkgutil_2/package'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/path_pkgutil_3'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/path_pkgutil_3/package'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/unicode_package'...
Listing './lib/python3.5/site-packages/astroid/tests/testdata/python3/data/unicode_package/core'...
Listing './lib/python3.5/site-packages/astroid-1.6.0.dist-info'...
Listing './lib/python3.5/site-packages/click'...
Listing './lib/python3.5/site-packages/click-6.7.dist-info'...
Listing './lib/python3.5/site-packages/cookies-2.2.1.dist-info'...
Listing './lib/python3.5/site-packages/coverage'...
Listing './lib/python3.5/site-packages/coverage/fullcoverage'...
Listing './lib/python3.5/site-packages/coverage/htmlfiles'...
Listing './lib/python3.5/site-packages/coverage-4.4.2.dist-info'...
Listing './lib/python3.5/site-packages/coveralls'...
Listing './lib/python3.5/site-packages/coveralls-1.1.dist-info'...
Listing './lib/python3.5/site-packages/docopt-0.6.2.egg-info'...
Listing './lib/python3.5/site-packages/filestack'...
Listing './lib/python3.5/site-packages/filestack/mixins'...
Listing './lib/python3.5/site-packages/filestack/models'...
Listing './lib/python3.5/site-packages/filestack/utils'...
Listing './lib/python3.5/site-packages/filestack_cli-1.2.1.egg-info'...
Listing './lib/python3.5/site-packages/filestack_python-2.2.1.egg-info'...
Listing './lib/python3.5/site-packages/fs_cli'...
Listing './lib/python3.5/site-packages/fs_cli/utils'...
Listing './lib/python3.5/site-packages/future'...
Listing './lib/python3.5/site-packages/future/backports'...
Listing './lib/python3.5/site-packages/future/backports/email'...
Listing './lib/python3.5/site-packages/future/backports/email/mime'...
Listing './lib/python3.5/site-packages/future/backports/html'...
Listing './lib/python3.5/site-packages/future/backports/http'...
Listing './lib/python3.5/site-packages/future/backports/test'...
Listing './lib/python3.5/site-packages/future/backports/urllib'...
Listing './lib/python3.5/site-packages/future/backports/xmlrpc'...
Listing './lib/python3.5/site-packages/future/builtins'...
Listing './lib/python3.5/site-packages/future/moves'...
Listing './lib/python3.5/site-packages/future/moves/dbm'...
Listing './lib/python3.5/site-packages/future/moves/html'...
Listing './lib/python3.5/site-packages/future/moves/http'...
Listing './lib/python3.5/site-packages/future/moves/test'...
Listing './lib/python3.5/site-packages/future/moves/tkinter'...
Listing './lib/python3.5/site-packages/future/moves/urllib'...
Listing './lib/python3.5/site-packages/future/moves/xmlrpc'...
Listing './lib/python3.5/site-packages/future/standard_library'...
Listing './lib/python3.5/site-packages/future/tests'...
Listing './lib/python3.5/site-packages/future/types'...
Listing './lib/python3.5/site-packages/future/utils'...
Listing './lib/python3.5/site-packages/future-0.16.0.egg-info'...
Listing './lib/python3.5/site-packages/httmock-1.2.6.egg-info'...
Listing './lib/python3.5/site-packages/httplib2'...
Listing './lib/python3.5/site-packages/httplib2-0.10.3.egg-info'...
Listing './lib/python3.5/site-packages/isort'...
Listing './lib/python3.5/site-packages/isort-4.2.15.dist-info'...
Listing './lib/python3.5/site-packages/lazy_object_proxy'...
Listing './lib/python3.5/site-packages/lazy_object_proxy-1.3.1.dist-info'...
Listing './lib/python3.5/site-packages/libfuturize'...
Listing './lib/python3.5/site-packages/libfuturize/fixes'...
Listing './lib/python3.5/site-packages/libpasteurize'...
Listing './lib/python3.5/site-packages/libpasteurize/fixes'...
Listing './lib/python3.5/site-packages/linecache2'...
Listing './lib/python3.5/site-packages/linecache2/tests'...
Listing './lib/python3.5/site-packages/linecache2-1.0.0.dist-info'...
Listing './lib/python3.5/site-packages/magicmock'...
Listing './lib/python3.5/site-packages/magicmock/ClientAPI'...
Compiling './lib/python3.5/site-packages/magicmock/ClientAPI/__init__.py'...
***   File "./lib/python3.5/site-packages/magicmock/ClientAPI/__init__.py", line 34
    print "unrecognized path list!"
                                  ^
SyntaxError: Missing parentheses in call to 'print'

Listing './lib/python3.5/site-packages/magicmock/Http'...
Compiling './lib/python3.5/site-packages/magicmock/Http/HttpHandler.py'...
***   File "./lib/python3.5/site-packages/magicmock/Http/HttpHandler.py", line 72
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/magicmock/Http/MockController.py'...
***   File "./lib/python3.5/site-packages/magicmock/Http/MockController.py", line 71
    print response
                 ^
SyntaxError: Missing parentheses in call to 'print'

Listing './lib/python3.5/site-packages/magicmock/Http/web'...
Compiling './lib/python3.5/site-packages/magicmock/Http/web/application.py'...
***   File "./lib/python3.5/site-packages/magicmock/Http/web/application.py", line 284
    except web.HTTPError, e:
                        ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/magicmock/Http/web/browser.py'...
***   File "./lib/python3.5/site-packages/magicmock/Http/web/browser.py", line 49
    print 'requesting', req.get_method(), req.get_full_url()
                     ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/magicmock/Http/web/contrib'...
Compiling './lib/python3.5/site-packages/magicmock/Http/web/db.py'...
***   File "./lib/python3.5/site-packages/magicmock/Http/web/db.py", line 81
    raise UnknownParamstyle, paramstyle
                           ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/magicmock/Http/web/debugerror.py'...
***   File "./lib/python3.5/site-packages/magicmock/Http/web/debugerror.py", line 283
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/magicmock/Http/web/form.py'...
***   File "./lib/python3.5/site-packages/magicmock/Http/web/form.py", line 100
    raise KeyError, i
                  ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/magicmock/Http/web/httpserver.py'...
***   File "./lib/python3.5/site-packages/magicmock/Http/web/httpserver.py", line 75
    except socket.error, socket_err:
                       ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/magicmock/Http/web/net.py'...
***   File "./lib/python3.5/site-packages/magicmock/Http/web/net.py", line 120
    raise ValueError, ':'.join(ip) + ' is not a valid IP address/port'
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/magicmock/Http/web/python23.py'...
***   File "./lib/python3.5/site-packages/magicmock/Http/web/python23.py", line 17
    raise AttributeError, name
                        ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/magicmock/Http/web/session.py'...
***   File "./lib/python3.5/site-packages/magicmock/Http/web/session.py", line 239
    raise ValueError, "Bad key: %s" % repr(key)
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/magicmock/Http/web/template.py'...
***   File "./lib/python3.5/site-packages/magicmock/Http/web/template.py", line 469
    raise ParseError, 'Unknown statement: %s' % repr(keyword)
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/magicmock/Http/web/utils.py'...
***   File "./lib/python3.5/site-packages/magicmock/Http/web/utils.py", line 75
    except KeyError, k:
                   ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/magicmock/Http/web/webapi.py'...
***   File "./lib/python3.5/site-packages/magicmock/Http/web/webapi.py", line 270
    raise ValueError, 'invalid characters in header'
                    ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/magicmock/Http/web/wsgiserver'...
Compiling './lib/python3.5/site-packages/magicmock/Http/web/wsgiserver/__init__.py'...
***   File "./lib/python3.5/site-packages/magicmock/Http/web/wsgiserver/__init__.py", line 616
    except ValueError, ex:
                     ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/magicmock/Http/web/wsgiserver/ssl_builtin.py'...
***   File "./lib/python3.5/site-packages/magicmock/Http/web/wsgiserver/ssl_builtin.py", line 43
    except ssl.SSLError, e:
                       ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/magicmock/Http/web/wsgiserver/ssl_pyopenssl.py'...
***   File "./lib/python3.5/site-packages/magicmock/Http/web/wsgiserver/ssl_pyopenssl.py", line 70
    except SSL.SysCallError, e:
                           ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/magicmock/Log'...
Listing './lib/python3.5/site-packages/magicmock/Sample'...
Listing './lib/python3.5/site-packages/magicmock/Sample/APITemplates'...
Listing './lib/python3.5/site-packages/magicmock/Sample/JsonTemplates'...
Listing './lib/python3.5/site-packages/magicmock/Sample/conf'...
Listing './lib/python3.5/site-packages/magicmock/Sample/ssl'...
Compiling './lib/python3.5/site-packages/magicmock/Utils.py'...
***   File "./lib/python3.5/site-packages/magicmock/Utils.py", line 170
    print self.method.upper() + ' ' + url
             ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/magicmock/__init__.py'...
***   File "./lib/python3.5/site-packages/magicmock/__init__.py", line 80
    print "Usage: magicmocksetup <dest dir>"
                                           ^
SyntaxError: Missing parentheses in call to 'print'

Listing './lib/python3.5/site-packages/magicmock-0.3.egg-info'...
Listing './lib/python3.5/site-packages/mccabe-0.6.1.dist-info'...
Listing './lib/python3.5/site-packages/mock'...
Listing './lib/python3.5/site-packages/mock/tests'...
Listing './lib/python3.5/site-packages/mock-2.0.0.dist-info'...
Listing './lib/python3.5/site-packages/past'...
Listing './lib/python3.5/site-packages/past/builtins'...
Listing './lib/python3.5/site-packages/past/tests'...
Listing './lib/python3.5/site-packages/past/translation'...
Listing './lib/python3.5/site-packages/past/types'...
Listing './lib/python3.5/site-packages/past/utils'...
Listing './lib/python3.5/site-packages/pbr'...
Listing './lib/python3.5/site-packages/pbr/cmd'...
Listing './lib/python3.5/site-packages/pbr/hooks'...
Listing './lib/python3.5/site-packages/pbr/tests'...
Listing './lib/python3.5/site-packages/pbr/tests/testpackage'...
Listing './lib/python3.5/site-packages/pbr/tests/testpackage/data_files'...
Listing './lib/python3.5/site-packages/pbr/tests/testpackage/doc'...
Listing './lib/python3.5/site-packages/pbr/tests/testpackage/doc/source'...
Listing './lib/python3.5/site-packages/pbr/tests/testpackage/pbr_testpackage'...
Listing './lib/python3.5/site-packages/pbr/tests/testpackage/pbr_testpackage/package_data'...
Listing './lib/python3.5/site-packages/pbr/tests/testpackage/src'...
Listing './lib/python3.5/site-packages/pbr-3.1.1.dist-info'...
Listing './lib/python3.5/site-packages/pip'...
Listing './lib/python3.5/site-packages/pip/_vendor'...
Listing './lib/python3.5/site-packages/pip/commands'...
Listing './lib/python3.5/site-packages/pip/compat'...
Listing './lib/python3.5/site-packages/pip/models'...
Listing './lib/python3.5/site-packages/pip/operations'...
Listing './lib/python3.5/site-packages/pip/req'...
Listing './lib/python3.5/site-packages/pip/utils'...
Listing './lib/python3.5/site-packages/pip/vcs'...
Listing './lib/python3.5/site-packages/pip-9.0.1.dist-info'...
Listing './lib/python3.5/site-packages/pkg_resources'...
Listing './lib/python3.5/site-packages/pkg_resources/_vendor'...
Listing './lib/python3.5/site-packages/pkg_resources/_vendor/packaging'...
Listing './lib/python3.5/site-packages/pkg_resources/extern'...
Listing './lib/python3.5/site-packages/pkg_resources-0.0.0.dist-info'...
Listing './lib/python3.5/site-packages/py'...
Listing './lib/python3.5/site-packages/py/_code'...
Listing './lib/python3.5/site-packages/py/_io'...
Listing './lib/python3.5/site-packages/py/_log'...
Listing './lib/python3.5/site-packages/py/_path'...
Listing './lib/python3.5/site-packages/py/_process'...
Listing './lib/python3.5/site-packages/py/_vendored_packages'...
Listing './lib/python3.5/site-packages/py-1.5.2.dist-info'...
Listing './lib/python3.5/site-packages/pylint'...
Listing './lib/python3.5/site-packages/pylint/checkers'...
Listing './lib/python3.5/site-packages/pylint/extensions'...
Listing './lib/python3.5/site-packages/pylint/pyreverse'...
Listing './lib/python3.5/site-packages/pylint/reporters'...
Listing './lib/python3.5/site-packages/pylint/reporters/ureports'...
Listing './lib/python3.5/site-packages/pylint/test'...
Listing './lib/python3.5/site-packages/pylint/test/data'...
Listing './lib/python3.5/site-packages/pylint/test/extensions'...
Listing './lib/python3.5/site-packages/pylint/test/extensions/data'...
Listing './lib/python3.5/site-packages/pylint/test/functional'...
Compiling './lib/python3.5/site-packages/pylint/test/functional/anomalous_unicode_escape_py2.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/anomalous_unicode_escape_py2.py", line 17
    RAW_UNICODE = ur"\u0062\n"
                             ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/pylint/test/functional/async_functions.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/async_functions.py", line 57
    async def func(a, a, b=[]):
         ^
SyntaxError: duplicate argument 'a' in function definition

Compiling './lib/python3.5/site-packages/pylint/test/functional/bad_except_order.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/bad_except_order.py", line 27
    __revision__ += 1
                   ^
SyntaxError: default 'except:' must be last

Compiling './lib/python3.5/site-packages/pylint/test/functional/class_members_py27.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/class_members_py27.py", line 24
    print self.nonexistent
             ^
SyntaxError: Missing parentheses in call to 'print'

Compiling './lib/python3.5/site-packages/pylint/test/functional/continue_in_finally.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/continue_in_finally.py", line 9
    continue # [continue-in-finally]
    ^
SyntaxError: 'continue' not supported inside 'finally' clause

Compiling './lib/python3.5/site-packages/pylint/test/functional/disable_msg_github_issue_1389.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/disable_msg_github_issue_1389.py", line 10
    place: PlaceId
         ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/pylint/test/functional/duplicate_argument_name.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/duplicate_argument_name.py", line 4
    def foo1(_, _): # [duplicate-argument-name]
                                              ^
SyntaxError: duplicate argument '_' in function definition

Compiling './lib/python3.5/site-packages/pylint/test/functional/exec_used_py2.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/exec_used_py2.py", line 3
    exec 'a = __revision__' # [exec-used]
                          ^
SyntaxError: Missing parentheses in call to 'exec'

Compiling './lib/python3.5/site-packages/pylint/test/functional/invalid_star_assignment_target.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/invalid_star_assignment_target.py", line 3
    *FIRST = [1, 2, 3] # [invalid-star-assignment-target]
                                                        ^
SyntaxError: starred assignment target must be in a list or tuple

Compiling './lib/python3.5/site-packages/pylint/test/functional/iterable_context_py2.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/iterable_context_py2.py", line 16
    print i
          ^
SyntaxError: Missing parentheses in call to 'print'

Compiling './lib/python3.5/site-packages/pylint/test/functional/misplaced_future.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/misplaced_future.py", line 3
    from __future__ import print_function # [misplaced-future]
                                                             ^
SyntaxError: from __future__ imports must occur at the beginning of the file

Compiling './lib/python3.5/site-packages/pylint/test/functional/nonlocal_and_global.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/nonlocal_and_global.py", line 5
    nonlocal missing
    ^
SyntaxError: name 'missing' is nonlocal and global

Compiling './lib/python3.5/site-packages/pylint/test/functional/nonlocal_without_binding.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/nonlocal_without_binding.py", line 22
    nonlocal b  # [nonlocal-without-binding]
    ^
SyntaxError: no binding for nonlocal 'b' found

Compiling './lib/python3.5/site-packages/pylint/test/functional/not_in_loop.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/not_in_loop.py", line 7
    continue # [not-in-loop]
    ^
SyntaxError: 'continue' not properly in loop

Compiling './lib/python3.5/site-packages/pylint/test/functional/old_division_manually.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/old_division_manually.py", line 2
    print 1 / 3
          ^
SyntaxError: Missing parentheses in call to 'print'

Compiling './lib/python3.5/site-packages/pylint/test/functional/print_always_warns.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/print_always_warns.py", line 8
    print "Python 3 fails to parse print statements." # [print-statement]
                                                    ^
SyntaxError: Missing parentheses in call to 'print'

Compiling './lib/python3.5/site-packages/pylint/test/functional/redefine_in_handler.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/redefine_in_handler.py", line 19
    except KeyError, exceptions.RuntimeError: # [redefine-in-handler]
                   ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/pylint/test/functional/return_outside_function.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/return_outside_function.py", line 2
    return # [return-outside-function]
                                     ^
SyntaxError: 'return' outside function

Compiling './lib/python3.5/site-packages/pylint/test/functional/star_needs_assignment_target.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/star_needs_assignment_target.py", line 3
    FIRST = *[1, 2]  # [star-needs-assignment-target]
           ^
SyntaxError: can't use starred expression here

Compiling './lib/python3.5/site-packages/pylint/test/functional/star_needs_assignment_target_py35.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/star_needs_assignment_target_py35.py", line 15
    UNPACK_IN_COMP = {elem for elem in (*range(10))} # [star-needs-assignment-target]
                                       ^
SyntaxError: can't use starred expression here

Compiling './lib/python3.5/site-packages/pylint/test/functional/syntax_error.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/syntax_error.py", line 1
    def toto # [syntax-error]
                            ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/pylint/test/functional/syntax_error_jython.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/syntax_error_jython.py", line 1
    def toto # [syntax-error]
                            ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/pylint/test/functional/too_many_star_expressions.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/too_many_star_expressions.py", line 3
    *FIRST, *SECOND = [1, 2, 3] # [too-many-star-expressions]
                                                            ^
SyntaxError: two starred expressions in assignment

Compiling './lib/python3.5/site-packages/pylint/test/functional/unpacked_exceptions.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/unpacked_exceptions.py", line 7
    except IOError, (errno, message):  # [unpacking-in-except]
                  ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/pylint/test/functional/yield_from_outside_func.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/yield_from_outside_func.py", line 2
    yield from [1, 2]  # [yield-outside-function]
                                                ^
SyntaxError: 'yield' outside function

Compiling './lib/python3.5/site-packages/pylint/test/functional/yield_inside_async_function.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/yield_inside_async_function.py", line 11
    yield 42 # [yield-inside-async-function]
    ^
SyntaxError: 'yield' inside async function

Compiling './lib/python3.5/site-packages/pylint/test/functional/yield_inside_async_function_py36.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/yield_inside_async_function_py36.py", line 11
    yield 42
    ^
SyntaxError: 'yield' inside async function

Compiling './lib/python3.5/site-packages/pylint/test/functional/yield_outside_func.py'...
***   File "./lib/python3.5/site-packages/pylint/test/functional/yield_outside_func.py", line 2
    yield 1  # [yield-outside-function]
                                      ^
SyntaxError: 'yield' outside function

Listing './lib/python3.5/site-packages/pylint/test/input'...
Compiling './lib/python3.5/site-packages/pylint/test/input/func_w0122_py_30.py'...
***   File "./lib/python3.5/site-packages/pylint/test/input/func_w0122_py_30.py", line 5
    exec 'a = __revision__'
                          ^
SyntaxError: Missing parentheses in call to 'exec'

Compiling './lib/python3.5/site-packages/pylint/test/input/func_w0332_py_30.py'...
***   File "./lib/python3.5/site-packages/pylint/test/input/func_w0332_py_30.py", line 4
    __revision__ = 1l
                    ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/pylint/test/input/func_w0401_package'...
Listing './lib/python3.5/site-packages/pylint/test/messages'...
Listing './lib/python3.5/site-packages/pylint/test/regrtest_data'...
Listing './lib/python3.5/site-packages/pylint/test/regrtest_data/absimp'...
Listing './lib/python3.5/site-packages/pylint/test/regrtest_data/bad_package'...
Compiling './lib/python3.5/site-packages/pylint/test/regrtest_data/bad_package/__init__.py'...
***   File "./lib/python3.5/site-packages/pylint/test/regrtest_data/bad_package/__init__.py", line 2
    raise missing.Missing..
                          ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/pylint/test/regrtest_data/beyond_top'...
Compiling './lib/python3.5/site-packages/pylint/test/regrtest_data/descriptor_crash.py'...
***   File "./lib/python3.5/site-packages/pylint/test/regrtest_data/descriptor_crash.py", line 20
    print p.getPage(sys.argv[1])
          ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/pylint/test/regrtest_data/dummy'...
Listing './lib/python3.5/site-packages/pylint/test/regrtest_data/dummy_plugin'...
Listing './lib/python3.5/site-packages/pylint/test/regrtest_data/package'...
Listing './lib/python3.5/site-packages/pylint/test/regrtest_data/package/subpackage'...
Listing './lib/python3.5/site-packages/pylint/test/regrtest_data/package_all'...
Compiling './lib/python3.5/site-packages/pylint/test/regrtest_data/py3k_error_flag.py'...
***   File "./lib/python3.5/site-packages/pylint/test/regrtest_data/py3k_error_flag.py", line 4
    raise Exception, 1  # Error emitted here with the Python 3 checker.
                   ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/pylint/test/regrtest_data/syntax_error.py'...
***   File "./lib/python3.5/site-packages/pylint/test/regrtest_data/syntax_error.py", line 1
    class A extends B {}
                  ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/pylint-1.7.1.dist-info'...
Listing './lib/python3.5/site-packages/pytest-3.0.7.dist-info'...
Listing './lib/python3.5/site-packages/pytest_cov'...
Listing './lib/python3.5/site-packages/pytest_cov-2.5.0.dist-info'...
Listing './lib/python3.5/site-packages/requests'...
Listing './lib/python3.5/site-packages/requests/packages'...
Listing './lib/python3.5/site-packages/requests/packages/chardet'...
Listing './lib/python3.5/site-packages/requests/packages/idna'...
Listing './lib/python3.5/site-packages/requests/packages/urllib3'...
Listing './lib/python3.5/site-packages/requests/packages/urllib3/contrib'...
Listing './lib/python3.5/site-packages/requests/packages/urllib3/packages'...
Listing './lib/python3.5/site-packages/requests/packages/urllib3/packages/backports'...
Listing './lib/python3.5/site-packages/requests/packages/urllib3/packages/ssl_match_hostname'...
Listing './lib/python3.5/site-packages/requests/packages/urllib3/util'...
Listing './lib/python3.5/site-packages/requests-2.13.0.dist-info'...
Listing './lib/python3.5/site-packages/requests_mock'...
Listing './lib/python3.5/site-packages/requests_mock/contrib'...
Listing './lib/python3.5/site-packages/requests_mock/tests'...
Listing './lib/python3.5/site-packages/requests_mock-1.3.0.dist-info'...
Listing './lib/python3.5/site-packages/responses-0.5.1.dist-info'...
Listing './lib/python3.5/site-packages/setuptools'...
Listing './lib/python3.5/site-packages/setuptools/command'...
Listing './lib/python3.5/site-packages/setuptools/extern'...
Listing './lib/python3.5/site-packages/setuptools-32.3.1.dist-info'...
Listing './lib/python3.5/site-packages/six-1.11.0.dist-info'...
Listing './lib/python3.5/site-packages/tests'...
Listing './lib/python3.5/site-packages/traceback2'...
Listing './lib/python3.5/site-packages/traceback2/tests'...
Listing './lib/python3.5/site-packages/traceback2-1.4.0.dist-info'...
Listing './lib/python3.5/site-packages/trafaret'...
Listing './lib/python3.5/site-packages/trafaret/contrib'...
Compiling './lib/python3.5/site-packages/trafaret/keys.py'...
***   File "./lib/python3.5/site-packages/trafaret/keys.py", line 11
    yield first, t.DataError(error=f'correct only if {second} is not defined'), (first,)
                                                                            ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/trafaret-0.9.0.dist-info'...
Listing './lib/python3.5/site-packages/unittest2'...
Listing './lib/python3.5/site-packages/unittest2/test'...
Listing './lib/python3.5/site-packages/unittest2-1.1.0.dist-info'...
Listing './lib/python3.5/site-packages/wrapt'...
Listing './lib/python3.5/site-packages/wrapt-1.10.11.egg-info'...
Listing './share'...
Listing './share/python-wheels'...
