Listing '.'...
Listing './bin'...
Listing './include'...
Listing './lib'...
Listing './lib/python3.5'...
Listing './lib/python3.5/site-packages'...
Listing './lib/python3.5/site-packages/appengine_template'...
Listing './lib/python3.5/site-packages/appengine_template/appengine_django'...
Compiling './lib/python3.5/site-packages/appengine_template/appengine_django/__init__.py'...
***   File "./lib/python3.5/site-packages/appengine_template/appengine_django/__init__.py", line 84
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/appengine_django/auth'...
Listing './lib/python3.5/site-packages/appengine_template/appengine_django/conf'...
Listing './lib/python3.5/site-packages/appengine_template/appengine_django/conf/app_template'...
Listing './lib/python3.5/site-packages/appengine_template/appengine_django/db'...
Compiling './lib/python3.5/site-packages/appengine_template/appengine_django/db/base.py'...
***   File "./lib/python3.5/site-packages/appengine_template/appengine_django/db/base.py", line 74
    except OSError, e:
                  ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/appengine_django/management'...
Listing './lib/python3.5/site-packages/appengine_template/appengine_django/management/commands'...
Compiling './lib/python3.5/site-packages/appengine_template/appengine_django/management/commands/runserver.py'...
***   File "./lib/python3.5/site-packages/appengine_template/appengine_django/management/commands/runserver.py", line 45
    print "Error: '%s' is not a valid port number." % port
                                                  ^
SyntaxError: Missing parentheses in call to 'print'

Listing './lib/python3.5/site-packages/appengine_template/appengine_django/serializer'...
Compiling './lib/python3.5/site-packages/appengine_template/appengine_django/serializer/python.py'...
***   File "./lib/python3.5/site-packages/appengine_template/appengine_django/serializer/python.py", line 125
    except ValueError, e:
                     ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/appengine_django/sessions'...
Listing './lib/python3.5/site-packages/appengine_template/appengine_django/sessions/backends'...
Listing './lib/python3.5/site-packages/appengine_template/appengine_django/tests'...
Compiling './lib/python3.5/site-packages/appengine_template/appengine_django/tests/__init__.py'...
***   File "./lib/python3.5/site-packages/appengine_template/appengine_django/tests/__init__.py", line 52
    exec "%s = item" % name
                   ^
SyntaxError: Missing parentheses in call to 'exec'

Compiling './lib/python3.5/site-packages/appengine_template/appengine_django/tests/integration_test.py'...
***   File "./lib/python3.5/site-packages/appengine_template/appengine_django/tests/integration_test.py", line 127
    except (IOError, httplib.HTTPException, socket.error), e:
                                                         ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/command.py'...
***   File "./lib/python3.5/site-packages/appengine_template/command.py", line 63
    print "Building new app: %s" % app_id
                               ^
SyntaxError: Missing parentheses in call to 'print'

Listing './lib/python3.5/site-packages/appengine_template/google_appengine'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/demos'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/demos/guestbook'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/apiproxy_rpc.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/apiproxy_rpc.py", line 131
    raise self.exception.__class__, self.exception, self.__traceback
                                  ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/apiproxy_stub_map.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 309
    except Exception, err:
                    ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/blobstore'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/blobstore/blobstore.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/blobstore/blobstore.py", line 205
    except apiproxy_errors.ApplicationError, e:
                                           ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/blobstore/blobstore_stub.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/blobstore/blobstore_stub.py", line 294
    except datastore_errors.EntityNotFoundError, err:
                                               ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/blobstore/file_blob_storage.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/blobstore/file_blob_storage.py", line 160
    except OSError, e:
                  ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/capabilities'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/channel'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/channel/channel.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/channel/channel.py", line 155
    except apiproxy_errors.ApplicationError, e:
                                           ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/croninfo.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/croninfo.py", line 69
    except groc.GrocException, e:
                             ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/datastore.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/datastore.py", line 930
    except (AssertionError, AttributeError, TypeError, ValueError), e:
                                                                  ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/datastore_admin.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/datastore_admin.py", line 144
    except apiproxy_errors.ApplicationError, err:
                                           ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/datastore_file_stub.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/datastore_file_stub.py", line 607
    except self.READ_PB_EXCEPTIONS, e:
                                  ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/datastore_types.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/datastore_types.py", line 354
    except (AssertionError, TypeError), e:
                                      ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/files'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/files/file.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/files/file.py", line 230
    except apiproxy_errors.ApplicationError, e:
                                           ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/images'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/images/__init__.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/images/__init__.py", line 563
    except apiproxy_errors.ApplicationError, e:
                                           ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/labs'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/labs/taskqueue'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/labs/taskqueue/taskqueue.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/labs/taskqueue/taskqueue.py", line 557
    except _RelativeUrlError, e:
                            ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/labs/taskqueue/taskqueue_stub.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/labs/taskqueue/taskqueue_stub.py", line 523
    except apiproxy_errors.ApplicationError, e:
                                           ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/lib_config.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/lib_config.py", line 154
    except ImportError, err:
                      ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/logservice'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/mail.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/mail.py", line 485
    except (Exception, Error), e:
                             ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/mail_stub.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/mail_stub.py", line 183
    except (IOError, OSError), e:
                             ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/memcache'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/namespace_manager'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/oauth'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/oauth/oauth_api.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/oauth/oauth_api.py", line 131
    except apiproxy_errors.ApplicationError, e:
                                           ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/prospective_search'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/prospective_search/prospective_search.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/prospective_search/prospective_search.py", line 349
    except apiproxy_errors.ApplicationError, e:
                                           ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/prospective_search/prospective_search_stub.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/prospective_search/prospective_search_stub.py", line 217
    self.regex = re.compile(ur'\b%s\b' % re.escape(unicode(text, 'utf-8')),
                                     ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/taskqueue'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/taskqueue/taskqueue.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/taskqueue/taskqueue.py", line 621
    except _RelativeUrlError, e:
                            ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/taskqueue/taskqueue_stub.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/taskqueue/taskqueue_stub.py", line 468
    except apiproxy_errors.ApplicationError, e:
                                           ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/urlfetch.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/urlfetch.py", line 346
    except apiproxy_errors.ApplicationError, err:
                                           ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/urlfetch_stub.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/urlfetch_stub.py", line 120
    except ValueError, e:
                     ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/users.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/users.py", line 235
    except apiproxy_errors.ApplicationError, e:
                                           ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/validation.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/validation.py", line 323
    except MissingAttribute, e:
                           ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/xmpp'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/xmpp/__init__.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/xmpp/__init__.py", line 157
    except apiproxy_errors.ApplicationError, e:
                                           ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/yaml_builder.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/yaml_builder.py", line 247
    raise NotImplementedError, 'Anchors not supported in this handler'
                             ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/yaml_listener.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/yaml_listener.py", line 175
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/yaml_object.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/api/yaml_object.py", line 171
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/base'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/cron'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/cron/GrocParser.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/cron/GrocParser.py", line 258
    except RecognitionException, re:
                               ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/datastore'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/datastore/datastore_query.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/datastore/datastore_query.py", line 560
    except (ValueError, TypeError), e:
                                  ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/datastore/datastore_rpc.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/datastore/datastore_rpc.py", line 298
    except KeyError, err:
                   ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/datastore/datastore_sqlite_stub.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/datastore/datastore_sqlite_stub.py", line 764
    except sqlite3.DatabaseError, e:
                                ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/datastore/sortable_pb_encoder.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/datastore/sortable_pb_encoder.py", line 80
    raise ProtocolBuffer.ProtocolBufferEncodeError, 'u16 too big'
                                                  ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/dist'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/dist/py_zipimport.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/dist/py_zipimport.py", line 133
    except (EnvironmentError, zipfile.BadZipfile), err:
                                                 ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/admin'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/admin/__init__.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/admin/__init__.py", line 106
    except IOError, e:
                  ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/admin/templates'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/admin_redirect'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/appstats'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/appstats/formatting.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/appstats/formatting.py", line 80
    if val >= 10L**99:
                ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/appstats/recording.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/appstats/recording.py", line 773
    except Exception, err:
                    ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/appstats/static'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/appstats/templates'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/appstats/ui.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/appstats/ui.py", line 64
    except Exception, err:
                    ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/blobstore'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/blobstore/blobstore.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/blobstore/blobstore.py", line 415
    except blobstore._CreationFormatError, err:
                                         ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/builtins'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/builtins/admin_redirect'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/builtins/appstats'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/builtins/datastore_admin'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/builtins/default'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/builtins/deferred'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/builtins/mapreduce'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/builtins/remote_api'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/bulkload'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/bulkload/bulkloader_config.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/bulkload/bulkloader_config.py", line 281
    except Exception, err:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/bulkload/bulkloader_parser.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/bulkload/bulkloader_parser.py", line 85
    except Exception, err:
                    ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/datastore_admin'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/datastore_admin/copy_handler.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/datastore_admin/copy_handler.py", line 170
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/datastore_admin/delete_handler.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/datastore_admin/delete_handler.py", line 155
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/datastore_admin/remote_api_put_stub.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/datastore_admin/remote_api_put_stub.py", line 131
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/datastore_admin/static'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/datastore_admin/templates'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/db'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/db/__init__.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/db/__init__.py", line 891
    except DerivedPropertyError, e:
                               ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/db/djangoforms.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/db/djangoforms.py", line 671
    except (db.BadValueError, ValueError), e:
                                         ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/deferred'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/deferred/deferred.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/deferred/deferred.py", line 128
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/ereporter'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/ereporter/templates'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/gql'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/gql/__init__.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/gql/__init__.py", line 456
    except ValueError, err:
                     ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/key_range'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/mapreduce'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/mapreduce/base_handler.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/mapreduce/base_handler.py", line 129
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/mapreduce/handlers.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/mapreduce/handlers.py", line 322
    taskqueue.TaskAlreadyExistsError), e:
                                     ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/mapreduce/input_readers.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/mapreduce/input_readers.py", line 419
    except ValueError, e:
                     ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/mapreduce/operation'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/mapreduce/static'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/mapreduce/status.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/mapreduce/status.py", line 236
    except (ValueError, yaml_errors.EventError), e:
                                               ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/mapreduce/util.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/mapreduce/util.py", line 94
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/preload'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/remote_api'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/remote_api/handler.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/remote_api/handler.py", line 307
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/search'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/testbed'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/webapp'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/webapp/__init__.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/webapp/__init__.py", line 286
    except UnicodeError, e:
                       ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/webapp/blobstore_handlers.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/webapp/blobstore_handlers.py", line 263
    except TypeError, err:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/webapp/util.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/webapp/util.py", line 126
    raise exc_info[0], exc_info[1], exc_info[2]
                     ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/webapp/xmpp_handlers.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/webapp/xmpp_handlers.py", line 69
    except xmpp.InvalidMessageError, e:
                                   ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/zipserve'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/zipserve/__init__.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/ext/zipserve/__init__.py", line 131
    except (IOError, RuntimeError, zipfile.BadZipfile), err:
                                                      ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/runtime'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/runtime/apiproxy.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/runtime/apiproxy.py", line 144
    raise new_exc.__class__, new_exc, tb
                           ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/tools'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/tools/appcfg.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/tools/appcfg.py", line 448
    except urllib2.URLError, e:
                           ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/tools/appengine_rpc.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/tools/appengine_rpc.py", line 226
    except urllib2.HTTPError, e:
                            ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/tools/bulkload_client.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/tools/bulkload_client.py", line 157
    except (IOError, httplib.HTTPException, socket.error), e:
                                                         ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/tools/bulkloader.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/tools/bulkloader.py", line 596
    except csv.Error, e:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/tools/dev_appserver.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/tools/dev_appserver.py", line 457
    except re.error, e:
                   ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/tools/dev_appserver_blobimage.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/tools/dev_appserver_blobimage.py", line 148
    raise ValueError, 'Invalid resize'
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/tools/dev_appserver_index.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/tools/dev_appserver_index.py", line 208
    except yaml_errors.EventListenerError, e:
                                         ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/tools/dev_appserver_main.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/tools/dev_appserver_main.py", line 226
    print sys.modules['__main__'].__doc__ % render_dict
            ^
SyntaxError: Missing parentheses in call to 'print'

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/tools/requeue.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/appengine/tools/requeue.py", line 115
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/net'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/net/proto'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/net/proto/ProtocolBuffer.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/net/proto/ProtocolBuffer.py", line 87
    raise ProtocolBufferDecodeError, '\n\t'.join(dbg)
                                   ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/net/proto2'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/net/proto2/proto'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/net/proto2/python'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/net/proto2/python/internal'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/net/proto2/python/internal/python_message.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/net/proto2/python/internal/python_message.py", line 750
    except struct.error, e:
                       ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/net/proto2/python/public'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/net/proto2/python/public/text_format.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/net/proto2/python/public/text_format.py", line 423
    except ValueError, e:
                     ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/pyglib'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/storage'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/storage/speckle'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/storage/speckle/proto'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/storage/speckle/python'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/google/storage/speckle/python/api'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/google/storage/speckle/python/api/rdbms_apiproxy.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/google/storage/speckle/python/api/rdbms_apiproxy.py", line 97
    except apiproxy_errors.ApplicationError, e:
                                           ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/antlr3'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/antlr3/antlr3'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/antlr3/antlr3/extras.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/antlr3/antlr3/extras.py", line 45
    except ImportError, exc:
                      ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/antlr3/antlr3/recognizers.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/antlr3/antlr3/recognizers.py", line 1151
    except NoViableAltException, re:
                               ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/antlr3/setup.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/antlr3/setup.py", line 49
    except OSError, exc:
                  ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/cacerts'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/bin'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/bin/compile-messages.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/bin/compile-messages.py", line 15
    print "This script should be run from the Django SVN tree or your project or app tree."
                                                                                          ^
SyntaxError: Missing parentheses in call to 'print'

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/bin/make-messages.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/bin/make-messages.py", line 23
    print "This script should be run from the django svn tree or your project or app tree."
                                                                                          ^
SyntaxError: Missing parentheses in call to 'print'

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/bin/profiling'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/bin/profiling/gather_profile_stats.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/bin/profiling/gather_profile_stats.py", line 24
    print "Processing %s" % f
                        ^
SyntaxError: Missing parentheses in call to 'print'

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/bin/unique-messages.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/bin/unique-messages.py", line 14
    print "this script should be run from the django svn tree or your project or app tree"
                                                                                         ^
SyntaxError: Missing parentheses in call to 'print'

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/conf'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/conf/__init__.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/conf/__init__.py", line 53
    raise EnvironmentError, "Environment variable %s is undefined." % ENVIRONMENT_VARIABLE
                          ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/conf/app_template'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/conf/locale'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/conf/project_template'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/conf/urls'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib/admin'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib/auth'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib/auth/__init__.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib/auth/__init__.py", line 13
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib/auth/create_superuser.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib/auth/create_superuser.py", line 88
    print "Superuser created successfully."
                                          ^
SyntaxError: Missing parentheses in call to 'print'

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib/auth/forms.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib/auth/forms.py", line 25
    raise validators.ValidationError, _('A user with that username already exists.')
                                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib/auth/management.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib/auth/management.py", line 31
    print "Adding permission '%s'" % p
                                 ^
SyntaxError: Missing parentheses in call to 'print'

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib/auth/models.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib/auth/models.py", line 20
    raise ValueError, "Got unknown password algorithm type in password."
                    ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib/comments'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib/contenttypes'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib/contenttypes/management.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib/contenttypes/management.py", line 24
    print "Adding content type '%s | %s'" % (ct.app_label, ct.model)
                                        ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib/csrf'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib/flatpages'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib/formtools'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib/humanize'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib/localflavor'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib/markup'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib/redirects'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib/sessions'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib/sessions/models.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib/sessions/models.py", line 82
    raise SuspiciousOperation, "User tampered with session cookie."
                             ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib/sitemaps'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib/sites'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib/sites/management.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib/sites/management.py", line 13
    print "Creating example.com Site object"
                                           ^
SyntaxError: Missing parentheses in call to 'print'

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib/sites/managers.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib/sites/managers.py", line 17
    raise ValueError, "%s couldn't find a field named %s in %s." % \
                    ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib/syndication'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib/syndication/feeds.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib/syndication/feeds.py", line 32
    raise ImproperlyConfigured, "Give your %s class a get_absolute_url() method, or define an item_link() method in your Feed class." % item.__class__.__name__
                              ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib/syndication/views.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/contrib/syndication/views.py", line 6
    raise Http404, "No feeds are registered."
                 ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/core'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/core/cache'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/core/cache/__init__.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/core/cache/__init__.py", line 34
    raise InvalidCacheBackendError, "Backend URI must start with scheme://"
                                  ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/core/handlers'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/core/handlers/base.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/core/handlers/base.py", line 26
    raise exceptions.ImproperlyConfigured, '%s isn\'t a middleware module' % middleware_path
                                         ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/core/mail.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/core/mail.py", line 32
    raise BadHeaderError, "Header values can't contain newlines (got %r for header %r)" % (val, name)
                        ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/core/management.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/core/management.py", line 479
    print "Running post-sync handlers for application", app_name
                                                     ^
SyntaxError: Missing parentheses in call to 'print'

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/core/serializers'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/core/servers'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/core/servers/basehttp.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/core/servers/basehttp.py", line 90
    self._headers[:] = [kv for kv in self._headers if kv[0].lower()<>name]
                                                                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/core/servers/fastcgi.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/core/servers/fastcgi.py", line 75
    print FASTCGI_HELP
                     ^
SyntaxError: Missing parentheses in call to 'print'

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/core/urlresolvers.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/core/urlresolvers.py", line 126
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/core/validators.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/core/validators.py", line 64
    raise ValidationError, gettext("This value must contain only letters, numbers and underscores.")
                         ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/db'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/db/__init__.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/db/__init__.py", line 12
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/db/backends'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/db/models'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/db/models/base.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/db/models/base.py", line 161
    raise TypeError, "'%s' is an invalid keyword argument for this function" % kwargs.keys()[0]
                   ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/db/models/loading.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/db/models/loading.py", line 30
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/db/models/manager.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/db/models/manager.py", line 16
    raise ValueError, "Model %s must specify a custom Manager, because it has a field named 'objects'" % cls.__name__
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/db/models/manipulators.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/db/models/manipulators.py", line 30
    raise AttributeError, "Manipulator cannot be accessed via instance"
                        ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/db/models/options.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/db/models/options.py", line 56
    raise TypeError, "'class Meta' got invalid attribute(s): %s" % ','.join(meta_attrs.keys())
                   ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/db/models/query.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/db/models/query.py", line 152
    except self.model.DoesNotExist, e:
                                  ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/db/transaction.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/db/transaction.py", line 195
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/dispatch'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/dispatch/dispatcher.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/dispatch/dispatcher.py", line 396
    except KeyError,err:
                   ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/dispatch/robust.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/dispatch/robust.py", line 53
    except Exception, err:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/dispatch/saferef.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/dispatch/saferef.py", line 112
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/forms'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/http'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/http/__init__.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/http/__init__.py", line 34
    raise KeyError, "%s not found in either POST or GET" % key
                  ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/middleware'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/middleware/common.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/middleware/common.py", line 44
    raise RuntimeError, "You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to %s%s (note the trailing slash), or set APPEND_SLASH=False in your Django settings." % (new_url[0], new_url[1])
                      ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/newforms'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/newforms/extras'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/newforms/fields.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/newforms/fields.py", line 466
    except ValidationError, e:
                          ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/newforms/forms.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/newforms/forms.py", line 182
    except ValidationError, e:
                          ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/oldforms'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/oldforms/__init__.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/oldforms/__init__.py", line 27
    raise KeyError, "Field %s not found\n%s" % (field_name, repr(self.fields))
                  ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/shortcuts'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/template'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/template/__init__.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/template/__init__.py", line 274
    except TemplateSyntaxError, e:
                              ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/template/context.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/template/context.py", line 76
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/template/defaultfilters.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/template/defaultfilters.py", line 564
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/template/defaulttags.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/template/defaulttags.py", line 272
    except TemplateSyntaxError, e:
                              ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/template/loader.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/template/loader.py", line 55
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/template/loader_tags.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/template/loader_tags.py", line 52
    raise TemplateSyntaxError, error_msg
                             ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/template/loaders'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/template/loaders/app_directories.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/template/loaders/app_directories.py", line 21
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/template/loaders/eggs.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/template/loaders/eggs.py", line 24
    raise TemplateDoesNotExist, template_name
                              ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/template/loaders/filesystem.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/template/loaders/filesystem.py", line 24
    raise TemplateDoesNotExist, error_msg
                              ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/templatetags'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/templatetags/i18n.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/templatetags/i18n.py", line 95
    raise TemplateSyntaxError, "'get_available_languages' requires 'as variable' (got %r)" % args
                             ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/test'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/test/client.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/test/client.py", line 172
    raise self.exc_info[1], None, self.exc_info[2]
                          ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/test/doctest.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/test/doctest.py", line 359
    raise TypeError, 'Expected a module: %r' % module
                   ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/test/simple.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/test/simple.py", line 40
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/test/utils.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/test/utils.py", line 48
    print "Creating test database..."
                                    ^
SyntaxError: Missing parentheses in call to 'print'

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/utils'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/utils/daemonize.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/utils/daemonize.py", line 11
    except OSError, e:
                  ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/utils/datastructures.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/utils/datastructures.py", line 136
    raise MultiValueDictKeyError, "Key %r not found in %r" % (key, self)
                                ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/utils/decorators.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/utils/decorators.py", line 21
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/utils/simplejson'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/utils/text.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/utils/text.py", line 177
    raise TypeError, s
                   ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/utils/translation'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/utils/translation/trans_real.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/utils/translation/trans_real.py", line 155
    except IOError, e:
                  ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/views'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/views/decorators'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/views/defaults.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/views/defaults.py", line 14
    raise http.Http404, "Content type %s object %s doesn't exist" % (content_type_id, object_id)
                      ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/views/generic'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/views/generic/create_update.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/views/generic/create_update.py", line 103
    raise Http404, "No %s found for %s" % (model._meta.verbose_name, lookup_kwargs)
                 ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/views/generic/date_based.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/views/generic/date_based.py", line 28
    raise Http404, "No %s available" % model._meta.verbose_name
                 ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/views/generic/list_detail.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/views/generic/list_detail.py", line 109
    raise AttributeError, "Generic detail view must be called with either an object_id or a slug/slug_field."
                        ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/views/i18n.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/views/i18n.py", line 164
    raise TypeError, k
                   ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/views/static.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/django/views/static.py", line 46
    raise Http404, "Directory indexes are not allowed here."
                 ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/docs'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_0_96/scripts'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/bin'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/bin/profiling'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/bin/profiling/gather_profile_stats.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/bin/profiling/gather_profile_stats.py", line 26
    print "Processing %s" % f
                        ^
SyntaxError: Missing parentheses in call to 'print'

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/bin/unique-messages.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/bin/unique-messages.py", line 14
    print "this script should be run from the django svn tree or your project or app tree"
                                                                                         ^
SyntaxError: Missing parentheses in call to 'print'

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/conf'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/conf/__init__.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/conf/__init__.py", line 74
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/conf/app_template'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/conf/locale'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/conf/project_template'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/conf/urls'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/contrib'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/contrib/admin'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/contrib/admindocs'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/contrib/admindocs/views.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/contrib/admindocs/views.py", line 326
    except template.InvalidTemplateLibrary, e:
                                          ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/contrib/auth'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/contrib/auth/__init__.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/contrib/auth/__init__.py", line 15
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/contrib/comments'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/contrib/contenttypes'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/contrib/contenttypes/management.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/contrib/contenttypes/management.py", line 26
    print "Adding content type '%s | %s'" % (ct.app_label, ct.model)
                                        ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/contrib/csrf'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/contrib/databrowse'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/contrib/flatpages'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/contrib/formtools'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/contrib/gis'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/contrib/humanize'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/contrib/localflavor'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/contrib/markup'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/contrib/markup/tests.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/contrib/markup/tests.py", line 69
    except AssertionError, e:
                         ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/contrib/messages'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/contrib/redirects'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/contrib/sessions'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/contrib/sitemaps'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/contrib/sites'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/contrib/sites/management.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/contrib/sites/management.py", line 12
    print "Creating example.com Site object"
                                           ^
SyntaxError: Missing parentheses in call to 'print'

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/contrib/syndication'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/contrib/webdesign'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/core'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/core/cache'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/core/files'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/core/files/move.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/core/files/move.py", line 82
    except OSError, e:
                  ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/core/files/storage.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/core/files/storage.py", line 173
    except OSError, e:
                  ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/core/files/uploadedfile.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/core/files/uploadedfile.py", line 78
    except OSError, e:
                  ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/core/files/uploadhandler.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/core/files/uploadhandler.py", line 207
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/core/handlers'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/core/handlers/base.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/core/handlers/base.py", line 41
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/core/mail'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/core/mail/__init__.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/core/mail/__init__.py", line 33
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/core/management'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/core/management/__init__.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/core/management/__init__.py", line 52
    except ImportError,e:
                      ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/core/management/base.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/core/management/base.py", line 210
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/core/management/sql.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/core/management/sql.py", line 166
    statement = re.sub(ur"--.*([\n\Z]|$)", "", statement)
                                        ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/core/serializers'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/core/servers'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/core/servers/basehttp.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/core/servers/basehttp.py", line 96
    self._headers[:] = [kv for kv in self._headers if kv[0].lower()<>name]
                                                                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/core/servers/fastcgi.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/core/servers/fastcgi.py", line 84
    print FASTCGI_HELP
                     ^
SyntaxError: Missing parentheses in call to 'print'

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/core/urlresolvers.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/core/urlresolvers.py", line 130
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/core/validators.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/core/validators.py", line 58
    except ValidationError, e:
                          ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/db'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/db/backends'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/db/backends/creation.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/db/backends/creation.py", line 28
    return '%x' % (abs(hash(args)) % 4294967296L)  # 2**32
                                               ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/db/models'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/db/models/base.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/db/models/base.py", line 890
    except ValidationError, e:
                          ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/db/models/query.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/db/models/query.py", line 189
    except self.model.DoesNotExist, e:
                                  ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/db/utils.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/db/utils.py", line 30
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/dispatch'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/dispatch/dispatcher.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/dispatch/dispatcher.py", line 208
    except Exception, err:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/dispatch/saferef.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/dispatch/saferef.py", line 121
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/forms'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/forms/extras'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/forms/fields.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/forms/fields.py", line 147
    except ValidationError, e:
                          ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/forms/forms.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/forms/forms.py", line 289
    except ValidationError, e:
                          ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/forms/formsets.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/forms/formsets.py", line 282
    except ValidationError, e:
                          ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/forms/models.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/forms/models.py", line 338
    except ValidationError, e:
                          ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/http'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/http/__init__.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/http/__init__.py", line 340
    except UnicodeError, e:
                       ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/http/multipartparser.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/http/multipartparser.py", line 197
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/middleware'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/middleware/common.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/middleware/common.py", line 61
    raise RuntimeError, (""
                      ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/middleware/csrf.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/middleware/csrf.py", line 28
    _MAX_CSRF_KEY = 18446744073709551616L     # 2 << 63
                                        ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/shortcuts'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/template'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/template/__init__.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/template/__init__.py", line 283
    except TemplateSyntaxError, e:
                              ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/template/context.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/template/context.py", line 125
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/template/debug.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/template/debug.py", line 73
    except TemplateSyntaxError, e:
                              ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/template/defaultfilters.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/template/defaultfilters.py", line 429
    starttag_re = re.compile(ur'<%s(/?>|(\s+[^>]*>))' % tags_re, re.U)
                                                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/template/defaulttags.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/template/defaulttags.py", line 308
    except TemplateSyntaxError, e:
                              ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/template/loader.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/template/loader.py", line 96
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/template/loaders'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/template/loaders/app_directories.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/template/loaders/app_directories.py", line 22
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/templatetags'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/test'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/test/_doctest.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/test/_doctest.py", line 383
    raise TypeError, 'Expected a module: %r' % module
                   ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/test/client.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/test/client.py", line 246
    except TemplateDoesNotExist, e:
                               ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/test/simple.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/test/simple.py", line 75
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/utils'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/utils/daemonize.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/utils/daemonize.py", line 6
    err_log='/dev/null', umask=022):
                                 ^
SyntaxError: invalid token

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/utils/decorators.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/utils/decorators.py", line 77
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/utils/encoding.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/utils/encoding.py", line 86
    except UnicodeDecodeError, e:
                             ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/utils/simplejson'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/utils/simplejson/decoder.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/utils/simplejson/decoder.py", line 139
    def JSONObject((s, end), encoding, strict, scan_once, object_hook, _w=WHITESPACE.match, _ws=WHITESPACE_STR):
                   ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/utils/simplejson/encoder.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/utils/simplejson/encoder.py", line 254
    False=False,
        ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/utils/simplejson/tool.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/utils/simplejson/tool.py", line 28
    except ValueError, e:
                     ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/utils/translation'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/utils/translation/trans_real.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/utils/translation/trans_real.py", line 131
    except IOError, e:
                  ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/views'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/views/decorators'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/django/views/generic'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/docs'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/docs/_ext'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/docs/_ext/applyxrefs.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/docs/_ext/applyxrefs.py", line 80
    print '%s: %s' % (fn, lines[0]),
                 ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/docs/_theme'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/docs/_theme/djangodocs'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/docs/faq'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/docs/howto'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/docs/howto/deployment'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/docs/internals'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/docs/internals/_images'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/docs/intro'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/docs/intro/_images'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/docs/man'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/docs/misc'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/docs/obsolete'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/docs/obsolete/_images'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/docs/ref'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/docs/ref/contrib'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/docs/ref/files'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/docs/ref/forms'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/docs/ref/models'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/docs/ref/templates'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/docs/releases'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/docs/topics'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/docs/topics/db'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/docs/topics/forms'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/docs/topics/http'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/docs/topics/i18n'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/extras'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/extras/csrf_migration_helper.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/extras/csrf_migration_helper.py", line 179
    except UnicodeDecodeError, e:
                             ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/scripts'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/aggregation'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/basic'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/basic/tests.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/basic/tests.py", line 18
    except error, e:
                ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/choices'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/custom_columns'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/custom_managers'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/custom_methods'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/custom_pk'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/defer'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/delete'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/empty'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/expressions'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/field_defaults'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/field_subclassing'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/files'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/fixtures'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/fixtures_model_package'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/force_insert_update'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/generic_relations'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/get_latest'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/get_object_or_404'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/get_or_create'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/invalid_models'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/lookup'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/lookup/tests.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/lookup/tests.py", line 407
    except FieldError, ex:
                     ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/m2m_and_m2o'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/m2m_intermediary'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/m2m_multiple'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/m2m_recursive'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/m2m_signals'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/m2m_through'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/m2o_recursive'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/many_to_many'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/many_to_one'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/many_to_one_null'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/model_forms'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/model_formsets'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/model_inheritance'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/model_inheritance_same_model_name'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/model_package'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/mutually_referential'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/one_to_one'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/or_lookups'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/order_with_respect_to'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/ordering'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/pagination'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/properties'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/proxy_model_inheritance'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/proxy_models'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/raw_query'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/reserved_names'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/reverse_lookup'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/save_delete_hooks'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/select_related'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/serializers'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/signals'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/str'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/test_client'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/transactions'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/unmanaged_models'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/update'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/user_commands'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/validation'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/validation/__init__.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/validation/__init__.py", line 10
    except ValidationError, e:
                          ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/validation/test_unique.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/validation/test_unique.py", line 94
    except ValidationError, e:
                          ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/modeltests/validators'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/admin_changelist'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/admin_inlines'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/admin_ordering'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/admin_registration'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/admin_scripts'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/admin_util'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/admin_validation'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/admin_validation/tests.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/admin_validation/tests.py", line 24
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/admin_views'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/admin_views/models.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/admin_views/models.py", line 221
    raise forms.ValidationError, "Grace is not a Zombie"
                               ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/admin_widgets'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/aggregation_regress'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/app_loading'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/app_loading/tests.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/app_loading/tests.py", line 80
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/backends'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/bash_completion'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/bug639'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/bug8245'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/bug8245/tests.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/bug8245/tests.py", line 15
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/builtin_server'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/cache'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/comment_tests'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/conditional_processing'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/context_processors'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/csrf_tests'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/custom_columns_regress'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/custom_columns_regress/tests.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/custom_columns_regress/tests.py", line 15
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/custom_managers_regress'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/datatypes'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/db_typecasts'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/decorators'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/defaultfilters'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/defaultfilters/tests.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/defaultfilters/tests.py", line 53
    self.assertEqual(addslashes(ur'\ : backslashes, too'),
                                                       ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/defer_regress'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/delete_regress'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/dispatch'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/expressions_regress'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/extra_regress'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/file_storage'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/file_storage/tests.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/file_storage/tests.py", line 39
    except error, e:
                ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/file_uploads'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/file_uploads/tests.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/file_uploads/tests.py", line 238
    except Exception, reference_error:
                    ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/fixtures_regress'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/fixtures_regress/tests.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/fixtures_regress/tests.py", line 370
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/forms'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/formwizard'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/generic_inline_admin'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/generic_relations_regress'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/get_or_create_regress'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/httpwrappers'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/humanize'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/i18n'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/i18n/tests.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/i18n/tests.py", line 127
    self.l = 10000L
                  ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/initial_sql_regress'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/inline_formsets'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/inline_formsets/tests.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/inline_formsets/tests.py", line 115
    except error, e:
                ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/inspectdb'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/introspection'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/locale'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/localflavor'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/m2m_regress'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/m2m_regress/tests.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/m2m_regress/tests.py", line 13
    except error, e:
                ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/m2m_through_regress'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/mail'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/makemessages'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/managers_regress'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/many_to_one_regress'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/max_lengths'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/middleware'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/middleware/tests.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/middleware/tests.py", line 77
    except RuntimeError, e:
                       ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/middleware_exceptions'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/middleware_exceptions/tests.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/middleware_exceptions/tests.py", line 30
    except TestException, e:
                        ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/model_fields'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/model_fields/tests.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/model_fields/tests.py", line 47
    except ValidationError, e:
                          ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/model_forms_regress'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/model_formsets_regress'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/model_inheritance_regress'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/model_inheritance_select_related'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/model_regress'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/modeladmin'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/modeladmin/tests.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/modeladmin/tests.py", line 310
    except error, e:
                ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/multiple_database'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/null_fk'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/null_fk_ordering'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/null_queries'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/one_to_one_regress'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/pagination_regress'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/queries'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/queries/tests.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/queries/tests.py", line 27
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/queryset_pickle'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/requests'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/reverse_single_related'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/select_related_onetoone'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/select_related_regress'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/serializers_regress'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/servers'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/settings_tests'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/signals_regress'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/sites_framework'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/special_headers'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/string_lookup'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/syndication'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/templates'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/templates/filters.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/templates/filters.py", line 87
    'filter-addslash01': ("{% autoescape off %}{{ a|addslashes }} {{ b|addslashes }}{% endautoescape %}", {"a": "<a>'", "b": mark_safe("<a>'")}, ur"<a>\' <a>\'"),
                                                                                                                                                               ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/templates/parser.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/templates/parser.py", line 47
    fe_test(ur'"Some \"Good\" News"', u'Some "Good" News')
                                   ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/templates/tests.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/templates/tests.py", line 232
    except template.TemplateSyntaxError, e:
                                       ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/templates/urls.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/templates/urls.py", line 15
    url(ur'^Юникод/(\w+)/$', views.client2, name=u"метка_оператора"),
                          ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/test_client_regress'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/test_client_regress/models.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/test_client_regress/models.py", line 38
    except AssertionError, e:
                         ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/test_runner'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/test_utils'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/text'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/urlpatterns_reverse'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/urlpatterns_reverse/tests.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/urlpatterns_reverse/tests.py", line 105
    except error, e:
                ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/utils'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/utils/datastructures.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/utils/datastructures.py", line 16
    except error, e:
                ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/utils/html.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/utils/html.py", line 117
    (ur'\ : backslashes, too', u'\\u005C : backslashes, too'),
                            ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/regressiontests/views'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/runtests.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/runtests.py", line 72
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/templates'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/templates/comments'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/templates/custom_admin'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/django_1_2/tests/templates/views'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/fancy_urllib'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/fancy_urllib/fancy_urllib'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/fancy_urllib/fancy_urllib/__init__.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/fancy_urllib/fancy_urllib/__init__.py", line 103
    raise socket.error, "Tunnel connection failed: %d %s" % (
                      ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/graphy'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/graphy/graphy'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/graphy/graphy/backends'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/graphy/graphy/backends/google_chart_api'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/ipaddr'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/ipaddr/ipaddr'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/ipaddr/ipaddr/ipaddr_test.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/ipaddr/ipaddr/ipaddr_test.py", line 225
    self.assertEqual(int(self.ipv4.netmask), 4294967040L)
                                                       ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/simplejson'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/simplejson/simplejson'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/simplejson/simplejson/decoder.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/simplejson/simplejson/decoder.py", line 130
    def JSONObject((s, end), encoding, strict, scan_once, object_hook, _w=WHITESPACE.match, _ws=WHITESPACE_STR):
                   ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/simplejson/simplejson/encoder.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/simplejson/simplejson/encoder.py", line 256
    False=False,
        ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/webob'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/webob/docs'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/webob/docs/comment-example-code'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/webob/docs/comment-example-code/example.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/webob/docs/comment-example-code/example.py", line 105
    except KeyError, e:
                   ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/webob/docs/wiki-example-code'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/webob/docs/wiki-example-code/example.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/webob/docs/wiki-example-code/example.py", line 70
    except exc.HTTPException, e:
                            ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/webob/tests'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/webob/tests/test_request.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/webob/tests/test_request.py", line 35
    print res
            ^
SyntaxError: Missing parentheses in call to 'print'

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/webob/webob'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/webob/webob/__init__.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/webob/webob/__init__.py", line 1181
    raise exc_info[0], exc_info[1], exc_info[2]
                     ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/webob/webob/byterange.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/webob/webob/byterange.py", line 121
    print begin, last_end
              ^
SyntaxError: Missing parentheses in call to 'print'

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/webob/webob/exc.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/webob/webob/exc.py", line 626
    except HTTPException, exc:
                        ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/webob/webob/headerdict.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/webob/webob/headerdict.py", line 98
    raise TypeError, "pop expected at most 2 arguments, got "\
                   ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/webob/webob/multidict.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/webob/webob/multidict.py", line 183
    raise TypeError, "pop expected at most 2 arguments, got "\
                   ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/webob/webob/util'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/webob/webob/util/dictmixin.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/webob/webob/util/dictmixin.py", line 56
    raise TypeError, "pop expected at most 2 arguments, got "\
                   ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/yaml'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/yaml/examples'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/yaml/examples/yaml-highlight'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/yaml/ext'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/yaml/lib'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/lib/yaml/lib/yaml'...
Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/yaml/lib/yaml/constructor.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/yaml/lib/yaml/constructor.py", line 129
    except TypeError, exc:
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/yaml/lib/yaml/reader.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/yaml/lib/yaml/reader.py", line 193
    except UnicodeDecodeError, exc:
                             ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/yaml/lib/yaml/resolver.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/yaml/lib/yaml/resolver.py", line 171
    re.compile(ur'''^(?:yes|Yes|YES|no|No|NO
                    |true|True|TRUE|false|False|FALSE
                    |on|On|ON|off|Off|OFF)$''', re.X),
                                            
                                                     
                                             ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/google_appengine/lib/yaml/lib/yaml/scanner.py'...
***   File "./lib/python3.5/site-packages/appengine_template/google_appengine/lib/yaml/lib/yaml/scanner.py", line 1426
    except UnicodeDecodeError, exc:
                             ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/google_appengine/new_project_template'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/templates'...
Listing './lib/python3.5/site-packages/appengine_template/google_appengine/tools'...
Listing './lib/python3.5/site-packages/appengine_template/media'...
Listing './lib/python3.5/site-packages/appengine_template/pytz'...
Compiling './lib/python3.5/site-packages/appengine_template/pytz/__init__.py'...
***   File "./lib/python3.5/site-packages/appengine_template/pytz/__init__.py", line 214
    raise ValueError, 'Not naive datetime (tzinfo is already set)'
                    ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/pytz/tzinfo.py'...
***   File "./lib/python3.5/site-packages/appengine_template/pytz/tzinfo.py", line 93
    raise ValueError, 'Not naive datetime (tzinfo is already set)'
                    ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/search'...
Listing './lib/python3.5/site-packages/appengine_template/search/pyporter2'...
Listing './lib/python3.5/site-packages/appengine_template/templates'...
Listing './lib/python3.5/site-packages/appengine_template/toolbox'...
Compiling './lib/python3.5/site-packages/appengine_template/toolbox/BeautifulSoup.py'...
***   File "./lib/python3.5/site-packages/appengine_template/toolbox/BeautifulSoup.py", line 448
    raise AttributeError, "'%s' object has no attribute '%s'" % (self.__class__.__name__, attr)
                        ^
SyntaxError: invalid syntax

Compiling './lib/python3.5/site-packages/appengine_template/toolbox/feedparser.py'...
***   File "./lib/python3.5/site-packages/appengine_template/toolbox/feedparser.py", line 287
    raise AttributeError, "object has no attribute '%s'" % key
                        ^
SyntaxError: invalid syntax

Listing './lib/python3.5/site-packages/appengine_template/toolbox/templatetags'...
Listing './lib/python3.5/site-packages/latimes_appengine_template-0.22.egg-info'...
Listing './lib/python3.5/site-packages/pip'...
Listing './lib/python3.5/site-packages/pip/_vendor'...
Listing './lib/python3.5/site-packages/pip/commands'...
Listing './lib/python3.5/site-packages/pip/compat'...
Listing './lib/python3.5/site-packages/pip/models'...
Listing './lib/python3.5/site-packages/pip/operations'...
Listing './lib/python3.5/site-packages/pip/req'...
Listing './lib/python3.5/site-packages/pip/utils'...
Listing './lib/python3.5/site-packages/pip/vcs'...
Listing './lib/python3.5/site-packages/pip-9.0.1.dist-info'...
Listing './lib/python3.5/site-packages/pkg_resources'...
Listing './lib/python3.5/site-packages/pkg_resources/_vendor'...
Listing './lib/python3.5/site-packages/pkg_resources/_vendor/packaging'...
Listing './lib/python3.5/site-packages/pkg_resources/extern'...
Listing './lib/python3.5/site-packages/pkg_resources-0.0.0.dist-info'...
Listing './lib/python3.5/site-packages/setuptools'...
Listing './lib/python3.5/site-packages/setuptools/command'...
Listing './lib/python3.5/site-packages/setuptools/extern'...
Listing './lib/python3.5/site-packages/setuptools-32.3.1.dist-info'...
Listing './share'...
Listing './share/python-wheels'...
